plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "E:\\DIPLOMA\\Sem 6 Microprojects\\BIS\\PhishignDetector\\frontend\\build"
publishOrigin = "ui"
commandOrigin = "ui"
base = "E:\\DIPLOMA\\Sem 6 Microprojects\\BIS\\PhishignDetector\\frontend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]